---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-frank-pv
spec:
  storageClassName: media-frank
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-frank-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-frank
  resources:
    requests:
      storage: 1Mi
