# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:Ua3NcwncOtJoYQZpUc2Fy2qo9ZaCxnDbI0GqvmdI4GJsq8JMRwQDIt7vKMq/uMVXLV3dfOXwQT9+osDq2a//5Mcb4LiuxB1/fFphbqrL9kaF5Nfa+8NJAy7HNV1eX2UxAQalxv6RUBf5u6sWMOfirlTjpd7ZN31H5nixugWvGk0DCHk=,iv:KE6O8U/QHdm9o2F5YaFiJa4yaNBsSn9DmsJ4A+5yZRQ=,tag:ZysXCkkNGNLO42COB8rP0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ysf5pwfe364d7yum0ulukj4475umzjlhcch9jeyy3j4geqvkq3rsw9jrk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3T1A1b21ORVp1TVdVd3N0
            SW1FNGVud0M1N2RISVdDdFhYYWpPM243YWlRCkk0NVB6bVNHYWR2MkFLcVc2VWJt
            U21CcUlqZ0lkekxNQWRwa1F1Y2dtVjQKLS0tIHlmWXdUMFhUWGJhM2xYcU0zWnpU
            SCt1ckc4R1FiRUg2SVZoWVZYK2c3dkEKetKSBPn6FV8gDpmWEnJ5a0Dl7VPq6ud1
            DW906Rc4onyFiHmfrPq0fUPoXNWp6708qvEl/6dJKWwDQ3P55X8lNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-08T01:18:05Z"
    mac: ENC[AES256_GCM,data:UX98j2+zhTkhBaktgaGPM5NfQ+NAy3fH6mz7PF7dbWmRjg3q8swniVJz70oXMujqBAY8Ik0xPXkDw8XwBC5VNjy9O6jwH63VkPF21Mt/xYfDIWbIPRDt3WOvx9fE4Ivd89oFixvpuvEFeRrOtS93psnNNTGLt7aJXjTwwwDqMdc=,iv:upoMlgndk/ADWNcSP5bDZLyuniKeoo+iGFkZocNnsMU=,tag:0FVhlAiPPLQOFO0BpqooDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
