---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    hajimari.io/enable: "true"
    hajimari.io/icon: "bot"
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN1}"
    external-dns/is-public: "true"
  #  hajimari.io/icon:
  name: bot
  namespace: networking
spec:
  rules:
    - host: bot.${SECRET_DOMAIN1}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: bot
                port:
                  number: 4545
  tls:
    - hosts:
        - bot.${SECRET_DOMAIN1}
---
apiVersion: v1
kind: Service
metadata:
  name: bot
  namespace: networking
  annotations: {}
spec:
  type: ExternalName
  externalName: "${NAS_ADDR}"
  ports:
    - port: 4545
