---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada-exporter
  namespace: monitoring
spec:
  interval: 5m
  releaseName: omada-exporter
  chart:
    spec:
      # renovate: registryUrl=https://charts.charliehaley.dev
      chart: omada-exporter
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: charlie-haley-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: chhaley/omada_exporter
      tag: "0.1.3"
    env:
      TZ: America/Detroit
      OMADA_INSECURE: true
      OMADA_HOST: "${OMADA_HOST}"
      OMADA_USER: "${OMADA_USER}"
      OMADA_PASS: "${OMADA_PASS}"
      OMADA_SITE: "${OMADA_SITE}"
    omada:
      insecure: true
    resources:
      requests:
        memory: 500Mi
        cpu: 35m
      limits:
        memory: 750Mi
