---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 11.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: mqtt
      namespace: home

  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2021.12.3
      nameOverride: "home-assistant"

    podAnnotations:
      secret.reloader.stakater.com/reload: home-assistant-secrets

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    env:
      TZ: "America/Detroit"
    envFrom:
      - secretRef:
          name: home-assistant

    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_HOME_ASSISTANT_ADDR}"
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "ha.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "ha.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config

    postgresql:
      enabled: true

      image:
        repository: bitnami/postgresql
        tag: 14.1.0
        pullPolicy: IfNotPresent

      persistence:
        enabled: true
        existingClaim: home-assistant-postgresql

      postgresqlUsername: home-assistant
      postgresqlDatabase: home-assistant


    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: v3.12.0
        git:
          deployKeySecret: code-server
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"

        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            hajimari.io/enable: "true"
            hajimari.io/icon: "code-bracescode-braces"
          hosts:
            - host: "ha-config.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "ha-config.${SECRET_DOMAIN}"

        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi

  valuesFrom:
    - kind: Secret
      name: home-assistant-pgsql
      valuesKey: postgresql_password
      targetPath: postgresql.postgresqlPassword
      optional: false
