---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blackbox-exporter
  - botkube
  - grafana
  - kube-prometheus-stack
  - loki
  - promtail
  # - pushgateway
  - snmp-exporter
  - speedtest-exporter
  - thanos
  - kured
  - influxdb
  - uptime-kuma
#  - omada-exporter
