---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nzbget
      version: 12.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/nzbget
      tag: 2021.11.25
    env:
      TZ: America/Detroit
      PUID: "99"
      PGID: "100"
    service:
      main:
        enabled: true
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hajimari.io/enable: "true"
          hajimari.io/icon: download-circle
          hajimari.io/group: downloads
        hosts:
          - host: nzbget.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - nzbget.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: nzbget-config
      media:
        enabled: true
        existingClaim: media-frank-pvc
        mountPath: /data
