---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: version-v5.24.0

    env:
      TZ: "America/Detroit"
      PGID: 65539

    persistence:
      config:
        enabled: true
        existingClaim: calibre-config
      data:
        enabled: true
        existingClaim: media-frank-pvc
        mountPath: /data

    service:
      main:
        ports:
          http:
            port: 8080
      webserver:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_CALIBRE_ADDR}"
        externalTrafficPolicy: Local
        ports:
          webserver:
            enabled: true
            port: 8081
            protocol: TCP
            targetPort: 8081

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hajimari.io/enable: "true"
          hajimari.io/icon: "bookshelf"
        hosts:
          - host: calibre.${SECRET_DOMAIN}
            paths:
              - path: /

        tls:
          - hosts:
              - "calibre.${SECRET_DOMAIN}"
