---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: youtubedl
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: youtubedl-material
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: tzahi12345/youtubedl-material
      tag: "nightly"
    env:
      TZ: "America/Detroit"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "eye-circle"
        hosts:
          - host: "ydl.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "ydl.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: youtubedl-config
        mountPath: /app/appdata
      media:
        enabled: true
        existingClaim: media-frank-pvc
        mountPath: /data
