---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.22.3.4523-d0ce30438
    env:
      TZ: "America/Detroit"
      ADVERTISE_IP: "http://${SVC_PLEX_ADDR}:32400/"
      ALLOWED_NETWORKS: "10.0.0.0/8,172.16.0.0/16,192.168.0.0/16"
      PLEX_CLAIM: "${SECRET_PLEX_CLAIM_TOKEN}"
    podSecurityContext:
      supplementalGroups:
      - 5600
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: "${SVC_PLEX_ADDR}"
      externalTrafficPolicy: Local
      port:
        port: 32400
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: https
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
      - host: "ptest.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "ptest.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-v1
      tmp:
        enabled: true
        emptyDir:
          enabled: true
          medium: "Memory"
      media:
        enabled: true
        existingClaim: media-frank-pvc
        mountPath: /data
    resources:
      limits:
        nvidia.com/gpu: 1
#    nodeSelector:
#      feature.node.kubernetes.io/pci-10de.present: "true"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k8s-7
    podAnnotations:
      configmap.reloader.stakater.com/reload: "plex-promtail"
    addons:
      promtail:
        enabled: true
        image:
          repository: grafana/promtail
          tag: 2.4.1
        loki: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
        logs:
        - name: promtail/plex
          path: "/config/Library/Application Support/Plex Media Server/Logs/*.log"
        - name: promtail/plex/plugins
          path: "/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/*.log"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        securityContext:
          runAsUser: 0
