---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: "192.168.44.50 - 192.168.44.254"
  METALLB_TRAEFIK_ADDR: "192.168.44.254"
  #
  NAS_ADDR: "192.168.44.2"
  GATEWAY_ADDR: "192.168.44.1"
  DNS01_ADDR: "192.168.44.3"
  #
  KUBE_VIP_ADDR: "192.168.44.10"
  KUBE_VIP_IFACE: "eth0"
  #
  SVC_EMQX_ADDR: "192.168.44.60"
  SVC_HOME_ASSISTANT_ADDR: "192.168.44.61"
  SVC_CALIBRE_ADDR: "192.168.44.70"
  SVC_QBITTORRENT_ADDRESS: "192.168.44.71"
  SVC_MINECRAFT_ELI_ADDR: "192.168.69.90"
  SVC_MINECRAFT_KATIE_ADDR: "192.168.69.91"
  SVC_INFLUXDB_ADDR: "192.168.44.51"
  SVC_PROMTAIL_ADDR: "192.168.44.52"
  SVC_SYSLOG_ADDR: "192.168.44.52"
  SVC_TRAEFIK_ADDR: "192.168.44.254"
  SVC_LONGHORN_ADDR: "192.168.44.253"
  SVC_PLEX_ADDR: "192.168.44.200"
  SVC_K8SDASH_ADDR: "192.168.44.250"
  SVC_OMADA_ADDRESS: "192.168.44.220"
