---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-frank-pv
spec:
  storageClassName: default-frank
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-frank-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default-frank
  resources:
    requests:
      storage: 1Mi
