---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: photoprism
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: photoprismdb
      namespace: default
  values:
    image:
      repository: photoprism/photoprism
      tag: "20220107"
    env:
      TZ: "America/Detroit"
      PHOTOPRISM_STORAGE_PATH: /photoprism/storage
      PHOTOPRISM_ORIGINALS_PATH: /data/photos
      PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM_ADMIN_PASS}"
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_IMPORT_PATH: /data/download/photo-import
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "photoprismdb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "root"
      PHOTOPRISM_DATABASE_PASSWORD: "${MYQSL_PASS}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "eye-circle"
        hosts:
          - host: "photos.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "photos.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: photoprism-config
        mountPath: /photoprism/storage
      data:
        enabled: true
        existingClaim: default-frank-pvc
        mountPath: /data
