---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  releaseName: qbittorrent
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.9
    podAnnotations:
      setGateway: "true"
    hostname: qbittorrent
    env:
      TZ: "America/Detroit"
    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_QBITTORRENT_ADDRESS}"
        ports:
          bittorrent:
            enabled: true
            port: 56059
            protocol: TCP
            targetPort: 56059
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "qb.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "qb.${SECRET_DOMAIN}"
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      media-nas:
        enabled: true
        existingClaim: media-frank-pvc
        mountPath: /data
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2m
    additionalContainers:
      - name: exporter
        image: esanchezm/prometheus-qbittorrent-exporter:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: QBITTORRENT_HOST
            value: "http://localhost"
          - name: QBITTORRENT_PORT
            value: "8080"
          - name: EXPORTER_PORT
            value: "9022"
          - name: EXPORTER_LOG_LEVEL
            value: "INFO"
          - name: METRICS_PREFIX
            value: "qbittorrent"
        ports:
          - name: metrics
            containerPort: 9022
