---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
  values:
    master:
      annotations:
        configmap.reloader.stakater.com/reload: "nfd-master-conf"
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      config: |-
        core:
          sources:
          - custom
          - pci
          - usb
        sources:
          usb:
            deviceClassWhitelist:
            - "02"
            - "03"
            - "0e"
            - "ef"
            - "fe"
            - "ff"
            deviceLabelFields:
            - "class"
            - "vendor"
            - "device"
          custom:
          - name: "zwave"
            matchOn:
            - usbId:
                vendor: ["10c4"]
                device: ["8a2a"]
          - name: "intel-gpu"
            matchOn:
            - pciId:
                class: ["0300"]
                vendor: ["8086"]
          - name: "nvidia-gpu"
            matchOn:
            - pciId:
                vendor: ["10de"]
