---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-config-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 200Mi

  storageClassName: ceph-block
