# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:gXDT3DiH1ixApC4CESt4aznvpCY9I4VhUU3uppP8u5TlmcH7HA==,iv:IrAxBtofA6LIdFLYPfA1U8DwLiUMHHomMfxDhExvNnk=,tag:QuLV1Sj19kOZJWZr7pm/Aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ysf5pwfe364d7yum0ulukj4475umzjlhcch9jeyy3j4geqvkq3rsw9jrk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQ3o5Vm5IVndyMVdaMXFq
            YWJFL3hvSDY3VDgzclJCSXZZKzd0RkJRaVFnCm1RcnpjM0YyOEZRNFVTbFJOV3Vv
            aCtoVUJPQWRoME9uQzZKSEkwN2NjUjQKLS0tIEZZM3NjUnpENk5XTnZWTUtMK2l2
            VVA4RFYwUCszaE5KWkswVTRaZVVaZ3cKmzKTp2YMmxz5HUwFP7MqUQE7K7zzv5dO
            Gurp0Jl2rl0dXclLEcWqvmyAJQq8P+o6yHlQV3CItGpLalT3Wkc6oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-07T17:15:19Z"
    mac: ENC[AES256_GCM,data:d9KJgxSPHzaTImJFU+htOIfK+utynW6/QMmpmDGfu1mmMTeZxuIGCy+aLGWtkO/egxy9MJcmo0RfpUOL4LICH+778syaP15WXG5jhENMDsHcA6/DXQo2pmFCBs92gXtdghwbEuexlZO7utUWQGEqdxndHdINaynCOMxKucw08oM=,iv:RQqEciCJ0CEGJJ9y2shHLcAIXu3ykbO/Zjg+Sqd4hNg=,tag:YMlup6+iQUN8ePLophVZ9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
