---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-config
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: ceph-block

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 100Mi

  storageClassName: ceph-block
