kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto-config
    namespace: home
stringData:
    mqtt.conf: ENC[AES256_GCM,data:sIdZzJ61mhbskPpMQqfAYafyuTeUi1J/dkWDDGpFGVqCa2D+h7WLeoW3+jlfO4fgzwcR5awx3JOGkeKHFsEc3o0qhXhQV7hebrksyWBL78rtGl8ue1Uf2T+SIM9nWaZIHVnrGXSIH8cSs494bvuZf+OWoVsHqcqQHa1TwfD6Kr2OaLrrJ1h96MW8YZBnmVtLc8bK2mKDLl4hj+L9R6EGReMR2JW3CoFGXw1T0BRRxiquoJ7E3DjKXzfBqg==,iv:JkwXdCNOKWF079DJVxOQ/pfX3WRDwdGpro/hrZt+buA=,tag:yjaydDEZIs8CJwK6hU93MA==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:afaQLoHNuxUu/m07baGSs2Bf9CgzriQUAskh18hvJDOuIehcPxy6jT6MJKaYkdaJoJGfDTxJ8TyzchYwE01rbdZhKUo3VyngfKyGstdugicoW9cw0DoVDq1/gGuBCRr/YdPoBZeUnYmp6ws/3FJljuDfqS0N4DVN,iv:nGGL0wN1Ju6/1KkBjqobfnrCQfg0TACrVhuFfnz+w1M=,tag:orJUi8o4Io4NrDA5/wEtCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ysf5pwfe364d7yum0ulukj4475umzjlhcch9jeyy3j4geqvkq3rsw9jrk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMTllTzNmYTAwQU1VbHJa
            VlJtRVR5bFlZb2M5S1VwL3pnMExYdUJnMlE0CjVvV3FPS1NOejliZVJDYmd6Ync1
            ZVhaRnVqbVN2WnhOK2FDY003Q0FCcWMKLS0tIGxPSXlGTXB6S1A1OFdEV3IxK3Yy
            cnlzYjBxOVAzN0I5MG9EcS82WjZVbWMK4qdSh7g0wmGxxiX/r4i+DuYI5uTyFc35
            sFKY9PaSEEQ3N6084EY3Xj0xDOVK2dwWLUXHT/LDjPBjh4gUSsslQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-18T02:37:08Z"
    mac: ENC[AES256_GCM,data:e288J4F/10SXXLKbSsLffYaZ/0uWOlBliKlFeL9W87fkWnneUwu10pa0AwvDpKCKnF0zF4/zNG5JWScruMhGbCLUuJ6IY9HPsjvbXrImGpvbIFdOZEI5pXb8EqNx+3T4U6903Zi7cs9SQ/Lkarqsly8vaom8aJna8Y2Er94twGQ=,iv:pJLFiW78P2itv5KAroSdKfkvRAcAHyQehjjvq31XkTI=,tag:GD+UB5g8tsP6rcba4xZELQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
