---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprismdb
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadbs
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    auth:
      rootPassword: "${FOUNDRY_ADMIN_KEY}"
      database: photoprism
      username: photoprism
      password: photoprism
    primary:
      args:
        - mysqld
        - --transaction-isolation=READ-COMMITTED
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --max-connections=512
        - --innodb-rollback-on-timeout=OFF
        - --innodb-lock-wait-timeout=50
    persistence:
      existingClaim: photoprism-db
