---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprismdb
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      version: 1.0.6
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/mariadb
      pullPolicy: IfNotPresent
      tag: "latest"
    secret:
      MYSQL_ROOT_PASSWORD: "${MYQSL_PASS}"
      MYSQL_PASSWORD: "${MYQSL_PASS}"
    args:
      - --transaction-isolation=READ-COMMITTED
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-connections=512
      - --innodb-rollback-on-timeout=OFF
      - --innodb-lock-wait-timeout=50
    env:
      TZ: America/Detroit
      MYSQL_ROOT_PASSWORD: "${MYQSL_PASS}"
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: "${MYQSL_PASS}"
    persistence:
      config:
        enabled: true
        mountPath: /var/lib/mysql
        existingClaim: photoprism-db
