---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprismdb
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/mariadb
      pullPolicy: IfNotPresent
      tag: "version-110.4.21mariabionic"
    env:
      TZ: America/Detroit
      MYSQL_ROOT_PASSWORD: "${FOUNDRY_ADMIN_KEY}"
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photoprism
    persistence:
      config:
        enabled: enabled
        mountPath: /config
        existingClaim: photoprism-db
