# yamllint disable
# comm_config.yaml: |
#     communications:
#         discord:
#             enabled: true
#             notiftype: short
#             token:
#             botid:
#             channel:
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:RJkejJxjwSKn1aNaHtrnDDPNwPDPRqE6bZSWyeHhDMMvidM/rPK+mR6c9nJpIaLLu+9Ux6uDytdMde+Nw994qZACCa0Ubdu/tLjuGIlvBRIvEUAQjezmBeD5jvLncITbmyIZKZ4YOFYZwl4KlHFSIaamLlvqodmnYA1YlluHfxuS+RmyIPANjjurdlcmZqR1GeHaGeFGmbh036T17foS47RfAi4CtxvgqgCHfd1x+GZTSX0B0UbYNGp2UKjUUImEZ/rZ/SXzK2vRxFy7KaCsU+J5qRuoOaYM2Noxvg==,iv:sjz23jHfwSMmIu6BBN1PZwMkzpAs3u0ygrQ1ecpx6Nc=,tag:I3NAu2emR1Qllo5rJJ9qYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ysf5pwfe364d7yum0ulukj4475umzjlhcch9jeyy3j4geqvkq3rsw9jrk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M1AxS2dzREdyRHBVWm93
            YWF2NUd6aE95ODE4aXBhbHRqNjJOeUZBQXljCmExQWFRM3hSMWZ0eElPYUJYMGxB
            eUZqMi9kbVNKVzJnZWhGcFppT0tnTG8KLS0tIGtnRkxpSHpmajdyRGY5NXhDR05k
            ckoybDV6TlZodW42WWMva2FhWDJLZWsKNyz3z54177W895YQCxfEXpNsWuH+cOQ8
            EiUQxG+Hgvqva6leh9Lph1GXsYQoPR+kdjNR29bE8kP697IdRdcEUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T21:54:33Z"
    mac: ENC[AES256_GCM,data:6CMlcdIGvcNGKRRy3voffdD1FberuGmxRUSdUEvRsqClvzY8NmT2ghAMIZ1DCRPiXsL6cTcnUSp1mQL0Or10MX+3gczmkEWgfTIL3mXZqa0ayNSURo52kM/jiT78EkzRz6EUIBotHKHNEhnrmxzKWyROK7PVWXKc+M0s8p6La8I=,iv:0oKzfgzlXJR8OfqTF0meASlYX3c6tu/zdno99zYuZrQ=,tag:WlrZ9H3jvib9Zs7iqNo1pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
