---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 200Mi
